query samplePokeAPIquery {
  pokemon_v2_pokemon(order_by: { id: asc }) {
    id
    order
    name
    height
    pokemon_v2_pokemonstats(order_by: { stat_id: asc }) {
      base_stat
      stat_id
    }
    pokemon_v2_pokemonspecy {
      pokemon_v2_pokemonspeciesnames(order_by: { language_id: asc }) {
        id
        language_id
        name
      }
    }
    pokemon_v2_pokemontypes(order_by: { type_id: asc }) {
      id
      slot
      type_id
    }
    pokemon_v2_pokemonabilities(order_by: { slot: asc }) {
      is_hidden
      slot
      ability_id
    }
    pokemon_v2_pokemonforms(order_by: { id: asc }) {
      id
      is_battle_only
      is_default
      is_mega
      form_name
      pokemon_v2_pokemonformnames(order_by: { language_id: asc }) {
        id
        name
        language_id
      }
    }
  }
  pokemon_v2_stat(order_by: { id: asc }) {
    id
    name
    pokemon_v2_statnames(order_by: { language_id: asc }) {
      id
      name
      language_id
    }
  }
  pokemon_v2_language(order_by: { id: asc }) {
    id
    name
  }
  pokemon_v2_type(order_by: { id: asc }) {
    id
    name
    pokemon_v2_typenames(order_by: { language_id: asc }) {
      id
      name
      language_id
    }
  }
  pokemon_v2_ability(order_by: { id: asc }) {
    id
    generation_id
    is_main_series
    name
    pokemon_v2_abilityflavortexts {
      flavor_text
      language_id
    }
    pokemon_v2_abilitynames {
      language_id
      name
    }
  }
}
